### ISSUE TITLE
Where is version 1.50?

### ISSUE THREAD

**Issue by ghost** [krolaw/fst#1]
According to the release history there should be version 1.50

**Comment by krolaw** [comment]
That's the current hosted source code, just hasn't been turned into a jar. Perhaps someone will do that, might be me if I get around to it.

**Comment by UltimateCD** [comment]
I see, i would appreciated if you could do that if you have the time

i am being using 1.42 for almost 2 years now 

Regardless i want to thank you for this little program its far better than the paid ones

**Comment by UltimateCD** [comment]
Any news for 1.50? Can you do it?

**Comment by krolaw** [comment]
Found and uploaded the last compiled binary from my archives (labelled 1.5). Internal code says 1.49b, so I guess I was testing before release. Nonetheless, that's the last version.
